version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432"
  backend:
    build:
      context: backend
      args:
        UID: ${UID:-1001}
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    user: rails
  client:
    build:
      context: client
      args:
        UID: ${UID:-1001}
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    user: nuxt